#!/usr/bin/env bash
# This is a script that installs nginx web server software on a physical server from scratch
apt-get update 
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.html
service nginx restart
