#!/usr/bin/env bash
# This is a script that installs nginx web server software on a physical server from scratch
apt-get update 
apt-get -y install nginx

# shellcheck disable=SC2148
cat <<EOF > /etc/nginx/sites-available/default
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx_debian.html;

	location / {
		try_files \$uri \$uri/ =404;
	}
	
	location = / {
		echo "HTTP/1.1 200 OK";
		echo "Content-Type: text/html";
		echo "";
		echo "Hello World";
	}
}
EOF
service nginx restart
