#!/usr/bin/env bash
# This is a script that installs nginx web server software on a physical server from scratch

apt-get update
apt-get -y install nginx

ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html

service nginx start

# define the string to be set as a replacement
str_replacement='server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent'

# use stream editor (sed) to search and replace in-place
sed -i "s/server_name _;/$str_replacement/" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
