#!/usr/bin/env bash
# This is a script that installs nginx web server software on a physical server from scratch
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.html

# Use sed to insert the redirection configuration into the Nginx default configuration
sudo sed -i '/server_name _;/a \\tlocation = /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
