#!/usr/bin/env bash
# This is a script that installs nginx web server software on a physical server from scratch

apt-get update
apt-get -y install nginx

# firewall allow
ufw allow "Nginx HTTP"

# populate index.html
echo "Hello World!" > /var/www/html/index.html

# handle redirections 
str_replacement='server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;'
sed -i "s/server_name _;/$str_replacement/" /etc/nginx/sites-enabled/default

# handle bad requests
touch /usr/share/nginx/html/404.html
e_tag=$(uuidgen)
str_repl="http {\\n\\tadd_header ETag $e_tag;\\n\\terror_code 404 /404.html;"
sed -i "s/http {/$str_repl/" /etc/nginx/nginx.conf

# Restart Nginx to apply the changes
service nginx restart
