#!/usr/bin/env bash
# This script automates haproxy load balancer installation and 
# configuration on a new Ubuntu Server

apt-get update

apt-get install haproxy

sed -i '$a\ENABLED=1' /etc/default/haproxy

mv /etc/haproxy/haproxy.cfg{,.original}

cat <<EOF >>/etc/haproxy/haproxy.cfg

frontend lb_01_client
        bind *:80
        mode http
        default_backend lb_01_server

backend lb_01_server
        balance roundrobin
        server web_01 100.26.120.42:80 check
        server web_02 3.86.18.239:80 check
EOF

service haproxy restart
