#!/usr/bin/env bash
# This script automates haproxy load balancer installation and 
# configuration on a new Ubuntu Server

apt-get -y update

apt-get -y install haproxy

sed -i '$a\ENABLED=1' /etc/default/haproxy

cat <<EOF >>/etc/haproxy/haproxy.cfg

frontend lb_01_client
        bind *:80
        mode http
        default_backend lb_01_server

backend lb_01_server
        balance roundrobin
        server 530760-web-01 100.26.120.42:80 check
        server 530760-web-02 3.86.18.239:80 check
EOF

service haproxy restart
