#!/usr/bin/env bash
# This script configures an nginx server to server a webpage
sudo apt update && sudo apt -y upgrade

sudo apt-get install -y curl nginx

sed -i 's_root \/usr\/share\/nginx\/html;_root \/var\/www\/html;_' /etc/nginx/sites-enabled/default

sed -i 's_index index.html index.htm;_index index.html index.nginx-debian.html;_' /etc/nginx/sites-enabled/default

sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen \[::\]:80 default_server;/' /etc/nginx/sites-enabled/default

service nginx restart
