#!/usr/bin/env bash
# This is a script that displays numbers from 1 to 100.
# Requirements:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number

f="Fizz"
b="Buzz"
fb="FizzBuzz"

for num in {1..100}
do
	if [ $(( num % 15 )) -eq 0 ]
	then
		echo "$fb"
	elif [ $(( num % 5 )) -eq 0 ]
	then
		echo "$b"
	elif [ $(( num % 3 )) -eq 0 ]
	then
		echo "$f"
	else
		echo $num
	fi
done
