#!/usr/bin/env bash
# This is a script that displays the content of the file /etc/passwd.
# Your script should only display:
# username
# user id
# Home directory path for the user

p=/etc/passwd
cnt=$(cat < $p|wc -l)
var=1

while [ $var -le "$cnt" ]
do
	cat < $p|head -$var|tail -1|cut -d ':' -f 1,3,6
	var=$(( var + 1 ))
done
