#!/usr/bin/env bash
# This is a script that displays the content of the file /etc/passwd.
# Your script should only display:
# username
# user id
# Home directory path for the user

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do
	echo -n "The user $f1 is part of the $f4 gang, lives in $f6 and rides "
	echo -n "$f7. $f3's place is protected by the passcode $f2, more info "
	echo "about the user here: $f5"
done < /etc/passwd
