#!/usr/bin/env bash
# This is a script that prints "Best School" 10 times

var=9
string="Best School"

until [ $var -eq 0 ]
do
        echo "$string"
        var=$(( var - 1 ))
        sleep 0.2
done
