#!/usr/bin/env bash
# This is the script that displays "Best School" 10 times, but for the 9th
# iteration, displays Best School and then Hi on a new line.

var=0
str_1="Best School"
str_2="Hi"

while [ $var -le 10 ]
do
        if [ $var -eq 9 ]
        then
                echo "$str_2"
        else
                echo "$str_1"
        fi
	var=$(( var + 1 ))
done
