#!/usr/bin/env bash
# This is a script that displays:
# The content of the current directory
# In a list format: Where only the part of the name after the first dash is
# displayed (refer to the example)

list=$(ls)
for line in $list
do
	echo "$line"|cut -d'-' -f2-
done
