#!/usr/bin/env bash
# Explanation

# Create the nginx user without login privileges
sudo useradd -r -d /var/cache/nginx -m -s /sbin/nologin nginx

# Define config file locations
NGINX_CONF="/etc/nginx/nginx.conf"
SITES_AVAIL="/etc/nginx/sites-available/default"

# Change the user directive to 'nginx'
sudo sed -i 's_^user .*_user nginx;_g' $NGINX_CONF

sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' $SITES_AVAIL
sudo sed -i 's/listen [::]:80 default_server;/listen [::]:8080 default_server;/g' $SITES_AVAIL

# Restart NGINX to apply changes
sudo service nginx restart
