#!/usr/bin/env bash
# Explanation

# Create the nginx user without login privileges
sudo useradd -r -d /var/cache/nginx -m -s /sbin/nologin nginx

# Define config file locations
NGINX_CONF="/etc/nginx/nginx.conf"
SITES_ENABLED="/etc/nginx/sites-enabled/default"

# Change the user directive to 'nginx'
sudo sed -i 's_^user .*_user nginx;_g' $NGINX_CONF

sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' $SITES_ENABLED
sudo sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/g' $SITES_ENABLED

# Restart NGINX to apply changes
sudo -u nginx service nginx start
