#!/usr/bin/env bash
# Debug web stack by running nginx with nginx user and listening on port
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf 
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo kill "$(pgrep -o apache2)"
sudo -u nginx service nginx start
